CREATE TABLE UTILISATEUR (
id_utilisateur int PRIMARY KEY NOT NULL,
nom VARCHAR (20), 
prénom VARCHAR (20), 
mail VARCHAR (50)) ;

CREATE TABLE MESSAGE (
id_message int PRIMARY KEY NOT NULL,
texte VARCHAR (300), 
ref_utilisateur int NOT NULL ,
ref_projet int NOT NULL ,
CONSTRAINT FK_REF_UTILISATEUR FOREIGN KEY (ref_utilisateur) REFERENCES UTILISATEUR(id_utilisateur),  
CONSTRAINT FK_REF_PROJET FOREIGN KEY (ref_projet) REFERENCES PROJET(id_projet) );

--AJOUTER LA COLONNE DATE DANS LA TABLE MESSAGE

CREATE TABLE PROJET (
id_projet int PRIMARY KEY NOT NULL , 
nom VARCHAR (20), 
description_projet VARCHAR (300) NOT NULL ) ;


CREATE TABLE ASSOCIE ( 
ref_utilisateur int NOT NULL, 
ref_projet int NOT NULL,
CONSTRAINT PK_ASSOCIE PRIMARY KEY (ref_utilisateur , ref_projet) ,
CONSTRAINT FK_ASSOCIE_REF_UTILISATEUR FOREIGN KEY (ref_utilisateur) REFERENCES UTILISATEUR(id_utilisateur),
CONSTRAINT FK_ASSOCIE_REF_PROJET FOREIGN KEY (ref_projet) REFERENCES PROJET(id_projet)) ;


CREATE TABLE CONSEILS (
id_conseil int PRIMARY KEY NOT NULL, 
message VARCHAR (500) NOT NULL, 
ref_projet int NOT NULL,
CONSTRAINT FK_CONSEIL_REF_PROJET FOREIGN KEY (ref_projet) REFERENCES PROJET(id_projet) );



CREATE TABLE MCD ( 
id_mcd int NOT NULL PRIMARY KEY,
fichier long,
ref_projet int NOT NULL,
CONSTRAINT FK_MCD_REF_PROJET FOREIGN KEY (ref_projet) REFERENCES PROJET(id_projet) );

CREATE TABLE CVO ( 
id_cvo int NOT NULL PRIMARY KEY,
fichier long,
ref_projet int NOT NULL,
CONSTRAINT FK_CVO_REF_PROJET FOREIGN KEY (ref_projet) REFERENCES PROJET(id_projet) );

CREATE TABLE BPMPN ( 
id_bpmn int NOT NULL PRIMARY KEY,
fichier long,
ref_projet int NOT NULL,
CONSTRAINT FK_BPMN_REF_PROJET FOREIGN KEY (ref_projet) REFERENCES PROJET(id_projet) );

CREATE TABLE STORY_MAP ( 
id_story_map int NOT NULL PRIMARY KEY,
fichier long,
ref_projet int NOT NULL,
CONSTRAINT FK_STORY_MAP_REF_PROJET FOREIGN KEY (ref_projet) REFERENCES PROJET(id_projet) );

CREATE TABLE MCF ( 
id_mcf int NOT NULL PRIMARY KEY,
fichier long,
ref_projet int NOT NULL,
CONSTRAINT FK_MCF_REF_PROJET FOREIGN KEY (ref_projet) REFERENCES PROJET(id_projet) );

CREATE TABLE PISCINE(
id_piscine int NOT NULL PRIMARY KEY,
nom VARCHAR (30) NOT NULL,
évènement int NOT NULL,
ref_bmpn int NOT NULL,
CONSTRAINT FK_PISCINE_REF_BPMN FOREIGN KEY (ref_bmpn) REFERENCES BPMPN(id_bpmn));

CREATE TABLE USER_STORY(
id_user_story int NOT NULL PRIMARY KEY,
contenu VARCHAR (300) NOT NULL,
ref_st int NOT NULL,
CONSTRAINT FK_USER_STORY_REF_ST FOREIGN KEY (ref_st) REFERENCES STORY_MAP(id_story_map));

CREATE TABLE EPIC(
id_epic int NOT NULL PRIMARY KEY,
evenement VARCHAR (300) NOT NULL,
ref_st int NOT NULL,
CONSTRAINT FK_EPIC_REF_ST FOREIGN KEY (ref_st) REFERENCES STORY_MAP(id_story_map));

CREATE TABLE ACTEURS(
id_acteur int NOT NULL PRIMARY KEY,
nom VARCHAR(30) NOT NULL,
interne VARCHAR (5) NOT NULL);





CREATE TABLE FLUX(
id_flux_mcf int NOT NULL PRIMARY KEY,
message VARCHAR (500) NOT NULL,
ref_acteur_émetteur int NOT NULL,
ref_acteur_récepteur int NOT NULL,
ref_mcf int NOT NULL,
CONSTRAINT FK_FLUX_REF_ACTEUR_EMETTEUR FOREIGN KEY (ref_acteur_émetteur) REFERENCES ACTEURS(id_acteur),
CONSTRAINT FK_FLUX_REF_ACTEUR_RECEPETEUR FOREIGN KEY (ref_acteur_récepteur) REFERENCES ACTEURS(id_acteur),
CONSTRAINT FK_FLUX_REF_MCF FOREIGN KEY (ref_mcf) REFERENCES ACTEURS(id_acteur));


CREATE TABLE couloir(
id_couloir int NOT NULL PRIMARY KEY,
nom VARCHAR (30) NOT NULL,
ref_piscine int NOT NULL,
CONSTRAINT FK_EPIC_REF_PISCINE FOREIGN KEY (ref_piscine) REFERENCES piscine(id_piscine));


CREATE TABLE FLUX_BPMN(
id_flux_bpmn int NOT NULL PRIMARY KEY,
message VARCHAR (500) NOT NULL,
ref_couloir int NOT NULL,
CONSTRAINT FK_FLUX_BPMN_REF_COULOIR FOREIGN KEY (ref_couloir) REFERENCES couloir(id_couloir));


CREATE TABLE ACTIVITE(
id_activite int NOT NULL PRIMARY KEY,
type_activité VARCHAR (30) NOT NULL,
évenement VARCHAR (30) NOT NULL,
est_sous_processus_ VARCHAR (3),
ref_couloir int NOT NULL,
CONSTRAINT FK_ACTIVITE_REF_COULOIR FOREIGN KEY (ref_couloir) REFERENCES couloir(id_couloir));
